[package]
name = "snake-tui"
version = "0.1.0"
edition = "2021"
default-run = "snake-tui"

[dependencies]
snake = { path = "../snake" }
ruscii = "0.3"
kira = { version = "0.7.3", features = ["cpal", "mp3"] }
